### ISSUE TITLE
ERROR | 2022-06-14 13:40:59,983 | main | com.vi.commonslib.service.ApplianceManagerService | init:175 | Catching java.net.ConnectException: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by rkumar-vi** [rkumar-vi/error#1]
ERROR | 2022-06-14 13:40:59,983 | main | com.vi.commonslib.service.ApplianceManagerService | init:175 | Catching java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1228)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at com.vi.commonslib.service.common.BaseHttpClient.getConnection(BaseHttpClient.java:74)
	at com.vi.commonslib.service.common.BaseHttpClient.get(BaseHttpClient.java:114)
	at com.vi.commonslib.service.common.JsonHttpClient.get(JsonHttpClient.java:116)
	at com.vi.commonslib.service.ApplianceManagerService.init(ApplianceManagerService.java:172)
	at com.vi.commonslib.service.ApplianceManagerService.<init>(ApplianceManagerService.java:143)
	at com.vi.commonslib.service.ApplianceManagerService.getInstance(ApplianceManagerService.java:158)
	at com.vi.commons.probe.service.ProbeProxyService.getApplianceUUID(ProbeProxyService.java:3676)
	at com.vi.commons.probe.service.ProbeProxyService.mainInit(ProbeProxyService.java:3647)
	at com.vi.commons.probe.service.ProbeProxyService.startProbeProxyService(ProbeProxyService.java:2162)
	at com.vi.commons.probe.service.ProbeProxyService.startProbeProxyService(ProbeProxyService.java:2143)
	at com.vi.probeSW.service.ProbeSWProxyServiceLauncher.launchProbeSWService(ProbeSWProxyServiceLauncher.java:62)
	at com.vi.probeSW.service.ProbeSWProxyServiceLauncher.main(ProbeSWProxyServiceLauncher.java:72)
 
 INFO | 2022-06-14 13:40:59,984 | main | com.vi.commonslib.service.ApplianceManagerService | getSystemUUID:738 | Could not get system UUID from AM. Waiting 5 seconds and trying again...  
 INFO | 2022-06-14 13:41:04,990 | main | com.vi.commonslib.service.ApplianceManagerService | getSystemUUID:738 | Could not get system UUID from AM. Waiting 5 seconds and trying again...

**Comment by rkumar-vi** [comment]
start tomcat first then localhost appliance.   If you stop probese in middle then socket connection is disturbed so restart tomcat also now. So sequence should be   A. tomcat --> B. probesw
