### ISSUE TITLE
"error":"not_implemented","reason":"all_or_nothing is not supported"

### ISSUE THREAD

**Issue by rkumar-vi** [rkumar-vi/error#17]
:"all_or_nothing is not supported"},{"id":"probestate-ProbeScaleioConfig","rev":"48-514e281a4db9ebd06a1e0a0a323df946","error":"not_implemented","reason":"all_or_nothing is not supported"}]
at org.lightcouch.CouchDbClientBase.validate(CouchDbClientBase.java:644)
at org.lightcouch.CouchDbClient$3.process(CouchDbClient.java:221)
at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:142)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:191)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
at org.lightcouch.CouchDbClientBase.executeRequest(CouchDbClientBase.java:468)
at org.lightcouch.CouchDbClientBase.post(CouchDbClientBase.java:606)
at org.lightcouch.CouchDbClientBase.bulk(CouchDbClientBase.java:371)
at com.vi.configstore.core.DocumentStoreClient.bulk(DocumentStoreClient.java:239)
at com.vi.configstore.core.ConfigStore.bulkSaveOrUpdate(ConfigStore.java:916)
at com.vi.service.IntegrationStatus.setEnabled(IntegrationStatus.java:230)
at com.vi.service.IntegrationStatus.setEnabled(IntegrationStatus.java:282)
at com.vi.service.IntegrationStatus.init(IntegrationStatus.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)

**Comment by rkumar-vi** [comment]
![Uploading Screenshot 2023-01-24 at 1.48.47 PM.png…]()

**Comment by rkumar-vi** [comment]
<img width="1761" alt="Screenshot 2023-01-24 at 1 48 47 PM" src="https://user-images.githubusercontent.com/104185795/214243151-685a1d71-6a5c-4210-8687-e94042d957c9.png">
