### ISSUE TITLE
 Failure is as follows: java.lang.RuntimeException: Node type already set: type=SWPhysicalPackage

### ISSUE THREAD

**Issue by rkumar-vi** [rkumar-vi/error#2]
DEBUG | 2022-06-14 17:07:04,701 | ProbeSWSNMPQuartzScheduler_Worker-2 | com.vi.commons.probe.service.ProbeProxyService | jobWasExecuted:2096 | Failure is as follows: java.lang.RuntimeException: Node type already set: type=SWPhysicalPackage
	at com.vi.graph.PropertyDelegate.setType(PropertyDelegate.java:56)
	at com.vi.graph.NxNode.setType(NxNode.java:171)
	at com.vi.graph.model.probesw.NxSWPhysicalPackage.setType(NxSWPhysicalPackage.java:204)
	at com.vi.probeSW.discovery.entity.SWPhysicalPackage.buildModel(SWPhysicalPackage.java:218)
	at com.vi.probeSW.dtf.DTFService.populate(DTFService.java:97)
	at com.vi.probeSW.dtf.DTFService.publish(DTFService.java:55)
	at com.vi.probeSW.discovery.collector.snmp.ProbeSWSNMPDiscoveryCollector.persistDiscoveredSwitches(ProbeSWSNMPDiscoveryCollector.java:200)
	at com.vi.probeSW.discovery.collector.snmp.ProbeSWSNMPDiscoveryCollector.collect(ProbeSWSNMPDiscoveryCollector.java:140)
	at com.vi.probeSW.discovery.collector.snmp.ProbeSWSNMPDiscoveryCollector.collect(ProbeSWSNMPDiscoveryCollector.java:60)
	at com.vi.commons.probe.collection.Collector.execute(Collector.java:607)
	at com.vi.commons.probe.scheduling.quartz.QuartzJob.execute(QuartzJob.java:56)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
 
DEBUG | 2022-06-14 17:07:05,273 | ProbeSWSNMPQuartzScheduler_Worker-2 | com.vi.commons.probe.service.DiscoveryMonitor | jobWasExecuted:120 | Notifying VI Health of manual discovery failure for job 10000027f8b22830  
DEBUG | 2022-06-14 17:07

**Comment by rkumar-vi** [comment]
in nxgraph you dont need to set type because it will be set by moelbuilder and type is saved in neo4j as label so it's important for a node
