### ISSUE TITLE
Catching java.io.FileNotFoundException: /data/collector/local/probeProbeSw/_Full_1_Jun14_17:16.json.gz (No such file or directory)

### ISSUE THREAD

**Issue by rkumar-vi** [rkumar-vi/error#3]
ERROR | 2022-06-14 17:20:07,552 | ProbeSWSNMPQuartzScheduler_Worker-2 | com.vi.graph.collector.upload.CollectorUploadService | upload:219 | Catching java.io.FileNotFoundException: /data/collector/local/probeProbeSw/_Full_1_Jun14_17:16.json.gz (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.vi.graph.collector.upload.CollectorUploadService.upload(CollectorUploadService.java:214)
	at com.vi.graph.collector.upload.ThriftPublisher.publish(CollectorUploadService.java:374)
	at com.vi.graph.collector.upload.CollectorUploadService.publish(CollectorUploadService.java:112)
	at com.vi.probeSW.dtf.DTFService.publish(DTFService.java:57)
	at com.vi.probeSW.discovery.collector.snmp.ProbeSWSNMPDiscoveryCollector.persistDiscoveredSwitches(ProbeSWSNMPDiscoveryCollector.java:200)

**Comment by rkumar-vi** [comment]
set in ~/service.conf

com.vi.graph.upload.dir=/Users/rupeshkumar/data/log
